backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pagina_inicio"
    label: "Página de Inicio"
    files:
      - label: "Inicio"
        name: "home"
        file: "src/pages/index.js"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Contenido", name: "body", widget: "text" }
