backend:
  name: git-gateway
  branch: main

collections:
  - name: "pagina_inicio"
    label: "Página de Inicio"
    files:
      - label: "Inicio"
        name: "home"
        file: "src/contenido/home.json"
        fields:
          - label: "Título principal"
            name: "hero_title"
            widget: "string"
          - label: "Subtítulo"
            name: "hero_subtitle"
            widget: "string"
          - label: "Texto del botón"
            name: "hero_cta"
            widget: "string"
