backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Página de Inicio"
    files:
      - label: "Inicio"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Subtítulo", name: "subtitle", widget: "string" }
          - { label: "Texto del botón", name: "ctaText", widget: "string" }
