hero:
  title: "Essentials for a cold winter"
  subtitle: "Discover Autumn Winter 2021"
  ctaText: "shop now"

highlight:
  title: "Luxury Knitwear"
  description: "This soft lambswool jumper is knitted in Scotland, using yarn from one of the world's oldest spinners based in Fife"
  textLink: "shop now"

quote:
  title: "about Sydney"
  quote: "We believe in two things: the pursuit of quality in everything we do, and looking after one another. Everything else should take care of itself."

sustainability:
  title: "We are Sustainable"
  subtitle: "From caring for our land to supporting our people, discover the steps we’re taking to do more for the world around us."
